### PR TITLE
add inclustion time

### LINKED ISSUE #23: Observer | Calculate transaction inclusion rate

### PR DESCRIPTION
**Pull request by faheelsattar**
closes #23

### CODE REVIEW

**Comment by voxil1010** [comment]
@jannikluhn I think from the users perspective seconds might be more informative since it actually use a time function to determine the delay, but we can definitely close it as well since we can use a query to determine it anyways, what do you say?

**Comment by faheelsattar** [comment]
@jannikluhn i think from the users perspective inclusion delay in seconds might make more sense since it actually uses a time function to measure it. But we can definitely do it using queries aswell, so should we close it?

**Comment by ulope** [comment]
I've already added a query to calculate the delay to the observer dashboard with the existing data in the DB. I wouldn't necessarily store it in the database.

However what would make sense is to think about if we can reorganize the data so it's easier to query (currently it requires group by and a couple of subqueries).

**Comment by faheelsattar** [comment]
alright i think then we will close it

**Comment by faheelsattar** [comment]
closing since calculating inclusion delay is already possible from queries

**Pull request closed without merging**
